/**
 * SPARK — S149 P5: ARCADE mode.
 *
 * *"you may not delete NONET … we will add ARCADE option to the front page below the Codex and add
 * bunch of minigames like the NONET SODOKU"* — owner, S149.
 *
 * The load-bearing property is the one that is easiest to break silently: **an arcade puzzle must
 * never touch simulation state.** `world.sudoku` is hashed and wire-carried, so a title-screen
 * puzzle written into it would be serialized, hashed, and inherited by the next match.
 */

import { describe, expect, it } from 'vitest';

import { CANVAS_HEIGHT, CANVAS_WIDTH } from '../constants.ts';
import { generateSudoku, isSolved, SUDOKU_N } from '../state/sudoku.ts';
import { makeWorld } from '../state/world.ts';
import { ARCADE_GAMES, arcadeBackGeom, arcadeRowGeoms, makeArcadeNonet } from './arcadeOverlay.ts';

describe('S149 P5 — the arcade roster', () => {
  it('ships NONET, the trial whose deletion the owner reversed', () => {
    expect(ARCADE_GAMES.map((g) => g.id)).toContain('nonet');
  });

  it('every entry has a distinct id — the menu hit-test keys on it', () => {
    const ids = ARCADE_GAMES.map((g) => g.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('no entry uses the reserved BACK id', () => {
    // `hitTest` returns either a game id or 'back'; a game called 'back' would be unreachable.
    expect(ARCADE_GAMES.map((g) => g.id)).not.toContain('back');
  });
});

describe('S149 P5 — the menu lays out on the board', () => {
  it('every row is on screen', () => {
    for (const r of arcadeRowGeoms()) {
      expect(r.x).toBeGreaterThanOrEqual(0);
      expect(r.x + r.w).toBeLessThanOrEqual(CANVAS_WIDTH);
      expect(r.y).toBeGreaterThanOrEqual(0);
      expect(r.y + r.h).toBeLessThanOrEqual(CANVAS_HEIGHT);
    }
  });

  it('BACK sits below the last row and never overlaps it', () => {
    const rows = arcadeRowGeoms();
    const back = arcadeBackGeom();
    const lastBottom = rows[rows.length - 1].y + rows[rows.length - 1].h;
    expect(back.y).toBeGreaterThan(lastBottom);
    expect(back.y + back.h).toBeLessThanOrEqual(CANVAS_HEIGHT);
  });

  it('rows never overlap each other, however many games are added', () => {
    // Driven with a synthetic roster so the guarantee holds for the "bunch of minigames" to come,
    // not just for today's single entry.
    const many = Array.from({ length: 6 }, (_, i) => ({
      id: `g${i}`, name: `G${i}`, blurb: '', tint: 0,
    }));
    const rows = arcadeRowGeoms(many);
    for (let i = 1; i < rows.length; i++) {
      expect(rows[i].y).toBeGreaterThanOrEqual(rows[i - 1].y + rows[i - 1].h);
    }
    expect(arcadeBackGeom(many).y).toBeGreaterThan(rows[rows.length - 1].y);
  });
});

describe('S149 P5 — ⛔ the arcade touches NO simulation state', () => {
  it('making an arcade puzzle does not write world.sudoku', () => {
    const w = makeWorld(0);
    expect(w.sudoku).toBeNull();
    makeArcadeNonet(12345);
    // THE assertion. If this ever fails, a title-screen puzzle is being serialized, hashed and
    // shipped to peers — and the next match starts with a NONET already in flight.
    expect(w.sudoku).toBeNull();
  });

  it('leaves every other sim field alone too', () => {
    const w = makeWorld(0);
    const before = JSON.stringify({
      tick: w.tick, phase: w.matchPhase, state: w.gameState,
      prims: w.primitives.size, fired: w.sudokuFiredThisMatch,
    });
    makeArcadeNonet(999);
    const after = JSON.stringify({
      tick: w.tick, phase: w.matchPhase, state: w.gameState,
      prims: w.primitives.size, fired: w.sudokuFiredThisMatch,
    });
    expect(after).toBe(before);
  });

  it('does NOT consume the once-per-match NONET latch', () => {
    // `sudokuFiredThisMatch` gates the in-match trial. If the arcade touched it, playing a puzzle on
    // the title screen would silently rob the player of the real trial in their next match.
    const w = makeWorld(0);
    makeArcadeNonet(1);
    makeArcadeNonet(2);
    expect(w.sudokuFiredThisMatch).toBe(false);
  });
});

describe('S149 P5 — the arcade plays the SHIPPED puzzle, not a lookalike', () => {
  it('is generated by the same generator the match trial uses, from the same seed', () => {
    const ev = makeArcadeNonet(4242);
    expect(ev.puzzle).toEqual(generateSudoku(4242));
  });

  it('a fresh seed yields a well-formed board', () => {
    const ev = makeArcadeNonet(7);
    expect(ev.puzzle.givens).toHaveLength(SUDOKU_N * SUDOKU_N);
    expect(ev.puzzle.solution).toHaveLength(SUDOKU_N * SUDOKU_N);
    // Every given agrees with the solution — otherwise the board is unsolvable as presented.
    for (let i = 0; i < ev.puzzle.givens.length; i++) {
      const g = ev.puzzle.givens[i];
      if (g !== 0) expect(g).toBe(ev.puzzle.solution[i]);
    }
  });

  it('the solution solves it, and a wrong grid does not', () => {
    const ev = makeArcadeNonet(11);
    expect(isSolved(ev.puzzle.solution, ev.puzzle.solution)).toBe(true);
    const wrong = ev.puzzle.solution.slice();
    wrong[0] = (wrong[0] % SUDOKU_N) + 1;
    expect(isSolved(wrong, ev.puzzle.solution)).toBe(false);
  });

  it('different seeds give different boards', () => {
    expect(makeArcadeNonet(1).puzzle.givens).not.toEqual(makeArcadeNonet(2).puzzle.givens);
  });

  it('starts UNSOLVED and UNRESOLVED — the match-only fields are inert here', () => {
    const ev = makeArcadeNonet(3);
    expect(ev.solvedBy).toBeNull();
    expect(ev.resolvedTick).toBeNull();
  });
});
