/**
 * SPARK — S165 P1. The race-unit ATLASES' contracts, as opposed to their pixels.
 *
 * ⭐ WHY THIS FILE EXISTS BEFORE THE RENDERER DOES. Twelve tracked asset files are regenerated by a
 * three-stage pipeline (design PNG → veo clips → atlas builder), and the loader they will eventually
 * feed fails SILENTLY: `goblinRenderer.ts:198-200` catches an atlas load error with a bare `catch {}`
 * and a comment saying the procedural puppet keeps the kind visible. So a regeneration that drops a
 * state, renames a row or changes a cell size ships invisibly and shows up only as a creature drawn
 * as a green blob. Exactly one test file anywhere in this repo reads `public/` art today.
 *
 * ⚠ WHAT THIS FILE CANNOT DO IS LOOK AT THE ART. A green suite is not evidence for render work —
 * the FIGHT banner shipped permanently oversized past a green suite, and this session's own vampire
 * ATTACK row shipped a weapon the design does not have, twice, past every automated check there is.
 * The contact sheet on a pure-black background is the other half and it is not automatable here.
 */

import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { ALL_RACES } from '../state/races.ts';

const PUBLIC = join(process.cwd(), 'public');
const onDisk = (base: string): string => join(PUBLIC, base.replace(/^\//, ''));

/**
 * ⛔ `/art/race-units/`, NOT `/godly/`. Same rule, and the same reason, as
 * `castleFrames.ts`'s `CASTLE_ATLAS_BASE`: `/godly/` is the one directory that means "a combo
 * shipped this art", and a castle-SPAWNED race unit is board furniture, not a combo output.
 * S164 filed these under the per-unit /godly/ anim directories and S165 moved them while nothing referenced them.
 */
const RACE_UNIT_ATLAS_BASE: Readonly<Record<string, string>> = Object.fromEntries(
  ALL_RACES.map((r) => [r, `/art/race-units/unit-${r}`]),
);

/** The rows the renderer can ask for. `die` is generated but NOT yet playable — see below. */
const PLAYABLE_STATES = ['idle', 'walk', 'attack'] as const;

interface Manifest {
  cellW: number;
  cellH: number;
  footAnchor: { x: number; y: number };
  states: Record<string, { row: number; frames: number; ticksPerFrame: number }>;
}

const manifests = ALL_RACES.map((race) => ({
  race,
  base: onDisk(RACE_UNIT_ATLAS_BASE[race]!),
}));

describe('every race ships both race-unit files, in the right directory', () => {
  it('ships the atlas AND its manifest for all six races', () => {
    for (const { race, base } of manifests) {
      expect(existsSync(`${base}-atlas.png`), `${race} atlas`).toBe(true);
      expect(existsSync(`${base}-anim.json`), `${race} manifest`).toBe(true);
    }
  });

  it('files under /art/race-units/ and NOT under /godly/, which means something else', () => {
    for (const race of ALL_RACES) {
      expect(RACE_UNIT_ATLAS_BASE[race]!.startsWith('/art/race-units/'), race).toBe(true);
      expect(RACE_UNIT_ATLAS_BASE[race]!.includes('/godly/'), race).toBe(false);
    }
  });

  it('covers exactly the six races, with no duplicate paths', () => {
    expect(Object.keys(RACE_UNIT_ATLAS_BASE).sort()).toEqual([...ALL_RACES].sort());
    const paths = Object.values(RACE_UNIT_ATLAS_BASE);
    expect(new Set(paths).size).toBe(paths.length);
  });
});

describe('the shipped manifests are usable by an atlas renderer', () => {
  const loaded = manifests.map(({ race, base }) => ({
    race,
    m: JSON.parse(readFileSync(`${base}-anim.json`, 'utf8')) as Manifest,
  }));

  it('every race declares every state the renderer can request', () => {
    for (const { race, m } of loaded) {
      for (const st of PLAYABLE_STATES) {
        expect(Object.keys(m.states), `${race} is missing "${st}"`).toContain(st);
      }
    }
  });

  it('every declared state has real frames and a real cadence', () => {
    for (const { race, m } of loaded) {
      for (const [name, st] of Object.entries(m.states)) {
        expect(st.frames, `${race}/${name} frames`).toBeGreaterThan(0);
        expect(st.ticksPerFrame, `${race}/${name} ticksPerFrame`).toBeGreaterThan(0);
        expect(Number.isInteger(st.row), `${race}/${name} row`).toBe(true);
      }
    }
  });

  it('rows are unique and contiguous from zero within each race', () => {
    for (const { race, m } of loaded) {
      const rows = Object.values(m.states).map((s) => s.row).sort((a, b) => a - b);
      expect(new Set(rows).size, `${race} duplicate rows`).toBe(rows.length);
      expect(rows, `${race} rows not contiguous from 0`).toEqual(rows.map((_, i) => i));
    }
  });

  /**
   * ⭐ THE CROSS-RACE ONE, AND IT IS THE POINT OF THE FILE.
   *
   * R94/R117 make all six castle units STAT-IDENTICAL, so they must also read as the same weight
   * class on the board. Each race is its OWN atlas, so the builder's union-bbox anti-jitter
   * guarantee — which holds within one atlas — does NOT span them: a single race whose cell is
   * taller renders that race's unit smaller at any shared sprite scale, and nothing catches it.
   * `cellH` is the height-fit divisor (`scale = cellH / bboxH`), so equal `cellH` across the six is
   * exactly the invariant that makes them peers.
   *
   * ⚠ `cellW` is deliberately NOT pinned: the builder widens the cell to fit the subject, and a
   * naga's tail legitimately needs more width than an imp. Width varies; height must not.
   */
  it('cellH is IDENTICAL across all six races — they are stat-identical siblings (R94/R117)', () => {
    const heights = loaded.map(({ race, m }) => ({ race, h: m.cellH }));
    const distinct = new Set(heights.map((x) => x.h));
    expect(
      distinct.size,
      `cellH differs across races: ${heights.map((x) => `${x.race}=${x.h}`).join(', ')}`,
    ).toBe(1);
  });

  it('every cell is a positive size and the foot anchor sits at the bottom of it', () => {
    for (const { race, m } of loaded) {
      expect(m.cellW, `${race} cellW`).toBeGreaterThan(0);
      expect(m.cellH, `${race} cellH`).toBeGreaterThan(0);
      expect(m.footAnchor.y, `${race} footAnchor.y`).toBeGreaterThan(0.9);
      expect(m.footAnchor.y, `${race} footAnchor.y`).toBeLessThanOrEqual(1);
    }
  });

  /**
   * ⚠ `die` IS GENERATED AND NOTHING PLAYS IT. `goblinRenderer.syncSprite` maps three FSM states
   * (ATTACKING→attack, SEEKING→walk, else idle) and creatures are REMOVED the instant they are
   * killed, so there is no window in which a death row could be seen. This asserts the row EXISTS
   * so the art is not silently lost in a future regeneration, and says plainly that it is unwired.
   * Making it visible needs a dying window in the sim, which is serialized state and its own work.
   */
  it('the die row exists in all six, even though nothing plays it yet', () => {
    for (const { race, m } of loaded) {
      expect(Object.keys(m.states), `${race} lost its die row`).toContain('die');
    }
  });
});
